static const int frontLeftSteerDeviceID = 1, frontLeftDriveDeviceID = 2, frontRightSteerDeviceID = 4, frontRightDriveDeviceID = 3;
  static const int rearLeftSteerDeviceID  = 5, rearLeftDriveDeviceID  = 6, rearRightSteerDeviceID  = 7, rearRightDriveDeviceID  = 8;
  const double reductionRatio = 8.31;
  const int WheelDiamter = 4;
  const double WheelCircufrence = 12.566;
  const double RadtoDeg = 57.2958;
  const double C_ExeTime = 0.01;
  const double C_L = 0.5969;
  const double C_W = 0.5969;
  const double C_R = 0.8441;
  const double C_PI = 3.14159265358979;